# Generated by Django 4.2.2 on 2023-06-27 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=2048)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("B", "Back-end"),
                            ("F", "Front-end"),
                            ("I", "IOS"),
                            ("A", "Android"),
                        ],
                        default="B",
                        max_length=2,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=2048)),
                (
                    "tag",
                    models.CharField(
                        choices=[("B", "Bug"), ("A", "Amélioration"), ("T", "Tâche")],
                        default="B",
                        max_length=2,
                    ),
                ),
                (
                    "prority",
                    models.CharField(
                        choices=[("F", "Faible"), ("M", "Moyenne"), ("E", "Elevée")],
                        default="E",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "A  faire"),
                            ("E", "En cours"),
                            ("T", "Terminé"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.CharField(max_length=1)),
                (
                    "role",
                    models.CharField(
                        choices=[("R", "Responsable"), ("C", "Collaborateur")],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "projects_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "users_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=2048)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="project.issues",
                    ),
                ),
            ],
        ),
    ]
