# Generated by Django 4.2.2 on 2023-06-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="author_user_id",
            new_name="author_user",
        ),
        migrations.RenameField(
            model_name="issues",
            old_name="author_user_id",
            new_name="author_user",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="author_user_id",
            new_name="author_user",
        ),
    ]
