# Generated by Django 4.2.2 on 2023-06-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="comment_author",
            new_name="author_user_id",
        ),
        migrations.RenameField(
            model_name="contributors",
            old_name="projects",
            new_name="projects_id",
        ),
        migrations.RenameField(
            model_name="contributors",
            old_name="users",
            new_name="users_id",
        ),
        migrations.RenameField(
            model_name="issues",
            old_name="issue_assignee_user",
            new_name="assignee_user_id",
        ),
        migrations.RenameField(
            model_name="issues",
            old_name="issue_author",
            new_name="author_user_id",
        ),
    ]
