# Generated by Django 4.2.2 on 2023-06-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_rename_comment_author_comments_author_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="staff",
        ),
        migrations.AlterField(
            model_name="comments",
            name="issue_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="project.issues",
            ),
        ),
        migrations.AlterField(
            model_name="issues",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="project.project",
            ),
        ),
    ]
