# Generated by Django 4.2.2 on 2023-06-28 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_rename_author_user_comments_author_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="users_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
