# Generated by Django 4.2.2 on 2023-06-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_project_author_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issues",
            old_name="prority",
            new_name="priority",
        ),
    ]
