# Generated by Django 4.2.2 on 2023-06-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_rename_prority_issues_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributors",
            old_name="projects_id",
            new_name="project_id",
        ),
        migrations.RenameField(
            model_name="contributors",
            old_name="users_id",
            new_name="user_id",
        ),
    ]
