# Generated by Django 4.2.2 on 2023-07-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_projects_id_contributors_project_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='project',
            new_name='project_id',
        ),
    ]
